### ISSUE TITLE
App crashes after login Activity

### ISSUE THREAD

**Issue by manas-droid** [The-SCRIPT-Group/Attendance#2]
Tried logging in using the same ERP Credentials as on the web app but the app crashed without giving any error message. To confirm I also tried to login from the web app, was successfully logged in.

**Comment by rittmang** [comment]
@manas-droid Gg

**Comment by manas-droid** [comment]
i checked out the code , i reckon the finish() method is called before startActivity() in the LoginActivity code. Maybe that's the reason of the glitch.

**Comment by akhilnarang** [comment]
Its possible something in the latest commit caused it, it hasn't really been tested.

**Comment by akhilnarang** [comment]
This should be fine, btw.
